# List of features with certain characteristics.


LOCALIZATION_FEATURES = ['CITY_OF_BIRTH',
'RESIDENCIAL_STATE',
'RESIDENCIAL_CITY',
'RESIDENCIAL_BOROUGH',
'RESIDENCIAL_PHONE_AREA_CODE',
'PROFESSIONAL_STATE',
'PROFESSIONAL_CITY',
'PROFESSIONAL_BOROUGH',
'PROFESSIONAL_PHONE_AREA_CODE']

UNIQUE_VALUES_FEATURES = ['CLERK_TYPE',
 'QUANT_ADDITIONAL_CARDS',
 'EDUCATION_LEVEL',
 'FLAG_MOBILE_PHONE',
 'FLAG_HOME_ADDRESS_DOCUMENT',
 'FLAG_RG',
 'FLAG_CPF',
 'FLAG_INCOME_PROOF',
 'FLAG_ACSP_RECORD',
 #Special banking account is repeated
 'QUANT_SPECIAL_BANKING_ACCOUNTS']

TWO_VALUE_LIST= ['POSTAL_ADDRESS_TYPE',
 'FLAG_RESIDENCIAL_PHONE',
 'FLAG_EMAIL',
 'FLAG_VISA',
 'FLAG_MASTERCARD',
 'FLAG_DINERS',
 'FLAG_AMERICAN_EXPRESS',
 'FLAG_OTHER_CARDS',
 'QUANT_CARS',
 'COMPANY',
 'FLAG_PROFESSIONAL_PHONE',
]

OTHERS_COLUMNS_DROPPED  = [ 
'MATE_PROFESSION_CODE',
'MATE_EDUCATION_LEVEL',
'PROFESSIONAL_ZIP_3'
]

CATEGORICAL_FEATURES = [
    'PAYMENT_DAY',
    'APPLICATION_SUBMISSION_TYPE',
    'SEX',
    'MARITAL_STATUS',
    'STATE_OF_BIRTH',
    'NACIONALITY',
    'RESIDENCE_TYPE',
    'PROFESSION_CODE',
    'OCCUPATION_TYPE',
    'PRODUCT',
    'RESIDENCIAL_ZIP_3',
    'POSTAL_ADDRESS_TYPE',
    'FLAG_EMAIL',
    'FLAG_RESIDENCIAL_PHONE',
    'FLAG_VISA',
    'FLAG_MASTERCARD',
    'FLAG_DINERS',
    'FLAG_AMERICAN_EXPRESS',
    'FLAG_OTHER_CARDS',
    'COMPANY',
    'FLAG_PROFESSIONAL_PHONE'
    
]


NUMERICAL_FEATURES = [
    'QUANT_DEPENDANTS',
    'MONTHS_IN_RESIDENCE',
    'PERSONAL_MONTHLY_INCOME',
    'OTHER_INCOMES',
    'PERSONAL_ASSETS_VALUE',
    'QUANT_CARS',
    'MONTHS_IN_THE_JOB',
    'AGE',
    'QUANT_BANKING_ACCOUNTS',
    
]

ALL_FEATURES = [
'CLERK_TYPE',
'PAYMENT_DAY',
'APPLICATION_SUBMISSION_TYPE',
'QUANT_ADDITIONAL_CARDS',
'POSTAL_ADDRESS_TYPE',
'SEX',
'MARITAL_STATUS',
'QUANT_DEPENDANTS',
'EDUCATION_LEVEL', 
'STATE_OF_BIRTH', 
'CITY_OF_BIRTH',
'NACIONALITY',
'RESIDENCIAL_STATE',
'RESIDENCIAL_CITY',
'RESIDENCIAL_BOROUGH',
'FLAG_RESIDENCIAL_PHONE',
'RESIDENCIAL_PHONE_AREA_CODE',
'RESIDENCE_TYPE', 
'MONTHS_IN_RESIDENCE',
'FLAG_MOBILE_PHONE',
'FLAG_EMAIL',
'PERSONAL_MONTHLY_INCOME',
'OTHER_INCOMES', 
'FLAG_VISA',
'FLAG_MASTERCARD',
'FLAG_DINERS',
'FLAG_AMERICAN_EXPRESS',
'FLAG_OTHER_CARDS', 
'QUANT_BANKING_ACCOUNTS',
'QUANT_SPECIAL_BANKING_ACCOUNTS',
'PERSONAL_ASSETS_VALUE', 
'QUANT_CARS',
'COMPANY', 
'PROFESSIONAL_STATE',
'PROFESSIONAL_CITY',
'PROFESSIONAL_BOROUGH', 
'FLAG_PROFESSIONAL_PHONE',
'PROFESSIONAL_PHONE_AREA_CODE',
'MONTHS_IN_THE_JOB', 
'PROFESSION_CODE',
'OCCUPATION_TYPE',
'MATE_PROFESSION_CODE',
'MATE_EDUCATION_LEVEL',
'FLAG_HOME_ADDRESS_DOCUMENT', 
'FLAG_RG', 
'FLAG_CPF',
'FLAG_INCOME_PROOF',
'PRODUCT', 
'FLAG_ACSP_RECORD',
'AGE',
'RESIDENCIAL_ZIP_3',
'PROFESSIONAL_ZIP_3'
        ]
